// @ts-check
import { defineConfig } from 'astro/config';
import react from '@astrojs/react';
import sitemap from '@astrojs/sitemap';

// Static-first Astro site for Cloudflare Pages (git-connected deploys).
// Islands are used only for the calculator (Phase 2) and the animation port.
export default defineConfig({
  site: 'https://www.alliancemutualescrow.com',
  output: 'static',
  integrations: [react(), sitemap()],
  image: {
    // AVIF + WebP responsive output is generated by astro:assets (sharp).
    responsiveStyles: true,
  },
  build: {
    // Inline tiny stylesheets, keep the rest as files with hashed names.
    assets: '_assets',
  },
  devToolbar: { enabled: false },
});
